/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookingResponse {
  bookingConfirmationCode?: string;
  checkInDate?: string;
  checkOutDate?: string;
  id?: number;
  numOfAdults?: number;
  numOfChildren?: number;
  roomType?: string;
  totalNumOfGuest?: number;
  userName?: string;
}
