/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookingRequest {
  bookingConfirmationCode?: string;
  checkInDate?: string;
  checkOutDate?: string;
  id?: number;
  numOfAdults?: number;
  numOfChildren?: number;
  roomId?: number;
  totalNumOfGuest?: number;
  userId?: number;
}
