/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoomRequest {
  id?: number;
  roomDescription?: string;
  roomPhotoUrl?: Blob;
  roomPrice: number;
  roomType: string;
}
