/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Booking } from '../models/booking';
export interface Room {
  bookings?: Array<Booking>;
  id?: number;
  roomDescription?: string;
  roomPhotoUrl?: string;
  roomPrice?: number;
  roomType?: string;
}
