/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Booking } from '../models/booking';
import { GrantedAuthority } from '../models/granted-authority';
import { Role } from '../models/role';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  bookings?: Array<Booking>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  email?: string;
  enable?: boolean;
  enabled?: boolean;
  id?: number;
  lastModifiedDate?: string;
  name?: string;
  password?: string;
  phone?: string;
  roles?: Array<Role>;
  username?: string;
}
