/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResponseUser } from '../../models/response-user';

export interface GetLoggedUserProfile$Params {
}

export function getLoggedUserProfile(http: HttpClient, rootUrl: string, params?: GetLoggedUserProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<ResponseUser>> {
  const rb = new RequestBuilder(rootUrl, getLoggedUserProfile.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResponseUser>;
    })
  );
}

getLoggedUserProfile.PATH = '/user/get-logged-in-profile-info';
