/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingResponse } from '../../models/booking-response';

export interface FindBookingByConfirmationCode$Params {
  'confirmation-code': string;
}

export function findBookingByConfirmationCode(http: HttpClient, rootUrl: string, params: FindBookingByConfirmationCode$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingResponse>> {
  const rb = new RequestBuilder(rootUrl, findBookingByConfirmationCode.PATH, 'get');
  if (params) {
    rb.path('confirmation-code', params['confirmation-code'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingResponse>;
    })
  );
}

findBookingByConfirmationCode.PATH = '/booking/get-by-confirmation-code/{confirmation-code}';
