spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingRoom_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: isi
    password: isi
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

#aws:
#  s3:
#    access-key: ${AWS_S3_ACCESS_KEY}
#    secret-key: ${AWS_S3_SECRET_KEY}
#    bucket-name: ${AWS_S3_BUCKET_NAME}

application:
#  file:
#    uploads:
#      photos-output-path: ./uploads
  security:
    jwt:
      secret-key: 133E635200446A586E3872057583782F413F9928472B4B6250645367566B5002
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8088


