/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BookingResponse } from '../models/booking-response';
import { cancelBooking } from '../fn/booking/cancel-booking';
import { CancelBooking$Params } from '../fn/booking/cancel-booking';
import { findBookingByConfirmationCode } from '../fn/booking/find-booking-by-confirmation-code';
import { FindBookingByConfirmationCode$Params } from '../fn/booking/find-booking-by-confirmation-code';
import { getAllBookings } from '../fn/booking/get-all-bookings';
import { GetAllBookings$Params } from '../fn/booking/get-all-bookings';
import { PageResponseBookingResponse } from '../models/page-response-booking-response';
import { saveBooking } from '../fn/booking/save-booking';
import { SaveBooking$Params } from '../fn/booking/save-booking';

@Injectable({ providedIn: 'root' })
export class BookingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveBooking()` */
  static readonly SaveBookingPath = '/booking/to-book';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveBooking()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveBooking$Response(params: SaveBooking$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return saveBooking(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveBooking$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveBooking(params: SaveBooking$Params, context?: HttpContext): Observable<string> {
    return this.saveBooking$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `findBookingByConfirmationCode()` */
  static readonly FindBookingByConfirmationCodePath = '/booking/get-by-confirmation-code/{confirmation-code}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findBookingByConfirmationCode()` instead.
   *
   * This method doesn't expect any request body.
   */
  findBookingByConfirmationCode$Response(params: FindBookingByConfirmationCode$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingResponse>> {
    return findBookingByConfirmationCode(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findBookingByConfirmationCode$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findBookingByConfirmationCode(params: FindBookingByConfirmationCode$Params, context?: HttpContext): Observable<BookingResponse> {
    return this.findBookingByConfirmationCode$Response(params, context).pipe(
      map((r: StrictHttpResponse<BookingResponse>): BookingResponse => r.body)
    );
  }

  /** Path part for operation `getAllBookings()` */
  static readonly GetAllBookingsPath = '/booking/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllBookings()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBookings$Response(params?: GetAllBookings$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBookingResponse>> {
    return getAllBookings(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllBookings$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBookings(params?: GetAllBookings$Params, context?: HttpContext): Observable<PageResponseBookingResponse> {
    return this.getAllBookings$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseBookingResponse>): PageResponseBookingResponse => r.body)
    );
  }

  /** Path part for operation `cancelBooking()` */
  static readonly CancelBookingPath = '/booking/cancel/{booking-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cancelBooking()` instead.
   *
   * This method doesn't expect any request body.
   */
  cancelBooking$Response(params: CancelBooking$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return cancelBooking(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cancelBooking$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  cancelBooking(params: CancelBooking$Params, context?: HttpContext): Observable<void> {
    return this.cancelBooking$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
