/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoomResponse } from '../../models/room-response';

export interface GetRoomById$Params {
  'room-id': number;
}

export function getRoomById(http: HttpClient, rootUrl: string, params: GetRoomById$Params, context?: HttpContext): Observable<StrictHttpResponse<RoomResponse>> {
  const rb = new RequestBuilder(rootUrl, getRoomById.PATH, 'get');
  if (params) {
    rb.path('room-id', params['room-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoomResponse>;
    })
  );
}

getRoomById.PATH = '/room/get-room-by-id/{room-id}';
