/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthenticationRequest } from './models/authentication-request';
export { AuthenticationResponse } from './models/authentication-response';
export { Booking } from './models/booking';
export { BookingRequest } from './models/booking-request';
export { BookingResponse } from './models/booking-response';
export { GrantedAuthority } from './models/granted-authority';
export { RegistrationRequest } from './models/registration-request';
export { ResponseUser } from './models/response-user';
export { Role } from './models/role';
export { Room } from './models/room';
export { RoomRequest } from './models/room-request';
export { RoomResponse } from './models/room-response';
export { RoomUpdateRequest } from './models/room-update-request';
export { User } from './models/user';
