/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

// @ts-ignore
export { AuthenticationRequest } from './models/authentication-request';
// @ts-ignore
export { AuthenticationResponse } from './models/authentication-response';
// @ts-ignore
export { Booking } from './models/booking';
// @ts-ignore
export { BookingRequest } from './models/booking-request';
// @ts-ignore
export { BookingResponse } from './models/booking-response';
// @ts-ignore
export { GrantedAuthority } from './models/granted-authority';
// @ts-ignore
export { PageResponseBookingResponse } from './models/page-response-booking-response';
// @ts-ignore
export { PageResponseResponseUser } from './models/page-response-response-user';
// @ts-ignore
export { PageResponseRoomResponse } from './models/page-response-room-response';
// @ts-ignore
export { RegistrationRequest } from './models/registration-request';
// @ts-ignore
export { ResponseUser } from './models/response-user';
// @ts-ignore
export { Role } from './models/role';
// @ts-ignore
export { Room } from './models/room';
// @ts-ignore
export { RoomRequest } from './models/room-request';
// @ts-ignore
export { RoomResponse } from './models/room-response';
// @ts-ignore
export { RoomUpdateRequest } from './models/room-update-request';
// @ts-ignore
export { User } from './models/user';
